#!/usr/bin/env python3
"""Scan the prose inside code comments and doc comments.

Handles JSDoc/TSDoc, Javadoc, KDoc, .NET XML docs, Doxygen, PHPDoc, rustdoc,
Go doc comments, Swift markup (C-family comments), Python docstrings and `#`
comments (tokenize), and `#` comments for Ruby/YARD, shell, YAML, Perl, R.

It masks the doc syntax (tags, types, parameter names, XML elements, code
examples, doctests), runs the prose checks from scan.py on what is left, and
adds doc-comment checks:
  echo-doc        the summary only restates the declaration ("Gets the user name." on GetUserName)
  param-echo      a parameter description only restates its name ("@param id The id.")
  returns-echo    "@returns The result."
  generated-doc   GhostDoc-style placeholders (<autogeneratedoc />, "TODO Edit XML Comment Template")
  this-method     "This method is used to...", "A helper function that..."

Usage:
  codedoc.py FILE [FILE ...] [--glossary MD] [--json]
  codedoc.py --lang .ts < source
  codedoc.py --same-code ORIGINAL REWRITTEN     exit 1 if anything but comments changed
  codedoc.py --selftest

Security posture: stdlib only, no network, no subprocess. Reads only the files it is given.
"""
from __future__ import annotations

import argparse
import collections
import difflib
import io
import json
import re
import sys
import time

sys.dont_write_bytecode = True  # keep the installed plugin folder clean
import tokenize
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import scan  # noqa: E402

C_FAMILY = {".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts", ".java", ".kt", ".kts", ".cs",
            ".go", ".rs", ".swift", ".php", ".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".m", ".mm",
            ".scala", ".dart", ".groovy", ".fs"}
HASH_FAMILY = {".rb", ".sh", ".bash", ".zsh", ".pl", ".pm", ".r", ".yaml", ".yml", ".toml", ".ex", ".exs",
               ".tf", ".ps1", ".nim", ".cr"}
PYTHON = {".py", ".pyi"}
STRINGS = {".json", ".arb", ".po", ".pot", ".resx", ".properties", ".strings", ".xlf", ".xliff"}
PROSE = {".md", ".mdx", ".markdown", ".txt", ".rst", ".adoc"}  # scanned whole, like scan.py (used by --diff)

# One regex per resource format; group "v" is the user-facing text.
STRING_VALUE = {
    ".json": re.compile(r'"(?P<k>(?:\\.|[^"\\])*)"\s*:\s*"(?P<v>(?:\\.|[^"\\])*)"'),
    ".po": re.compile(r'^msgstr(?:\[\d+\])?\s+"(?P<v>(?:\\.|[^"\\])*)"', re.M),
    ".resx": re.compile(r"<value>(?P<v>[^<]*)</value>"),
    ".properties": re.compile(r"^\s*(?![#!])[^=:\s]+\s*[=:]\s*(?P<v>.+)$", re.M),
    ".strings": re.compile(r'"(?:\\.|[^"\\])*"\s*=\s*"(?P<v>(?:\\.|[^"\\])*)"\s*;'),
    ".xlf": re.compile(r"<target[^>]*>(?P<v>[^<]*)</target>"),
}
STRING_VALUE.update({".arb": STRING_VALUE[".json"], ".pot": STRING_VALUE[".po"], ".xliff": STRING_VALUE[".xlf"]})
PLACEHOLDER = re.compile(r"\{\{[^}]*\}\}|\{[\w.,\s]*\}|%(?:\d+\$)?[sdif@]|\$t\([^)]*\)|<[^>]+>|\\[nt]")
LOCALE_IN_PATH = re.compile(r"(?:^|[\\/._-])([a-z]{2})(?:[-_]([A-Z]{2}|[a-z]{2}))?(?=[\\/._-]|$)")

C_TOKEN = re.compile(
    r'(?P<str>"(?:\\.|[^"\\\n])*"|\'(?:\\.|[^\'\\\n])*\'|`(?:\\.|[^`\\])*`)'
    r"|(?P<block>/\*.*?\*/)|(?P<line>//[^\n]*)",
    re.S,
)
# ponytail: Rust lifetimes ('a) and C# verbatim strings (@"") can confuse the string match; rare in doc lines
HASH_TOKEN = re.compile(r'(?P<str>"(?:\\.|[^"\\\n])*"|\'(?:\\.|[^\'\\\n])*\')|(?P<line>#[^\n]*)')

FILLER = set("""a an the of to for this that given specified current new instance method function class
property value object gets get sets set or and returns return is by with from in on it its be
constructor ctor default main""".split())

TAG_WITH_NAME = r"(?:param|arg|argument|prop|property|typeparam|template|tparam|throws|exception|raises|field)"


@dataclass
class Block:
    start: int          # 1-based line of the first comment line
    lines: list[str]    # comment text with comment markers stripped, one per source line
    doc: bool           # a doc comment (/** */, ///, docstring, Go/Ruby leading comments)
    decl: str           # the declaration line it documents, "" if unknown


def split_ident(text: str) -> set[str]:
    words = re.findall(r"[A-Z]+(?=[A-Z][a-z]|\d|\b)|[A-Z]?[a-z]+|\d+", text)
    return {stem(w.lower()) for w in words}


ABBREV = {"identifier": "id", "number": "num", "string": "str", "index": "idx", "configuration": "config",
          "cfg": "config", "message": "msg", "error": "err", "context": "ctx", "request": "req",
          "response": "res", "argument": "arg", "parameter": "param", "value": "val", "length": "len",
          "directory": "dir", "information": "info", "button": "btn", "source": "src",
          "destination": "dst", "callback": "cb", "count": "cnt", "temporary": "tmp", "character": "char"}


def stem(word: str) -> str:
    word = word[:-1] if len(word) > 3 and word.endswith("s") and not word.endswith("ss") else word
    return ABBREV.get(word, word)


def strip_markers(raw: str) -> list[str]:
    out = []
    for line in raw.split("\n"):
        line = re.sub(r"^\s*(?:/\*\*!?|/\*!?|\*/|\*(?!/)|///?!?|//|#+'?|\"\"\"|''')", "", line, count=1)
        out.append(re.sub(r"\*/\s*$", "", line).rstrip())
    return out


def next_decl(lines: list[str], after: int) -> str:
    """First code line after a comment, skipping blanks, annotations and attributes."""
    for line in lines[after:after + 8]:
        s = line.strip()
        if s and not re.match(r"^(?:@|\[|#\[|//|/\*|\*|#)", s):
            return s
    return ""


def c_blocks(src: str, ext: str) -> list[Block]:
    lines = src.split("\n")
    blocks: list[Block] = []
    for m in C_TOKEN.finditer(src):
        if m.lastgroup == "str":
            continue
        start = src.count("\n", 0, m.start()) + 1
        raw = m.group()
        end = start + raw.count("\n")
        if m.lastgroup == "block":
            doc = raw.startswith(("/**", "/*!")) and raw != "/**/"
            blocks.append(Block(start, strip_markers(raw), doc, next_decl(lines, end)))
            continue
        doc = raw.startswith(("///", "//!")) or ext == ".go"
        prev = blocks[-1] if blocks else None
        own_line = lines[start - 1].lstrip().startswith("//")
        if prev and own_line and prev.start + len(prev.lines) == start and prev.doc == doc and not prev.lines[0].startswith("/*"):
            prev.lines += strip_markers(raw)  # merge consecutive // lines into one block
            prev.decl = next_decl(lines, start)
        else:
            blocks.append(Block(start, strip_markers(raw), doc and own_line, next_decl(lines, start)))
    return blocks


def hash_blocks(src: str) -> list[Block]:
    lines = src.split("\n")
    blocks: list[Block] = []
    for m in HASH_TOKEN.finditer(src):
        if m.lastgroup == "str" or m.group().startswith("#!"):
            continue
        start = src.count("\n", 0, m.start()) + 1
        own_line = lines[start - 1].lstrip().startswith("#")
        prev = blocks[-1] if blocks else None
        if prev and own_line and prev.start + len(prev.lines) == start:
            prev.lines += strip_markers(m.group())
            prev.decl = next_decl(lines, start)
        else:
            blocks.append(Block(start, strip_markers(m.group()), own_line, next_decl(lines, start)))
    return blocks


def py_blocks(src: str) -> list[Block]:
    lines = src.split("\n")
    blocks: list[Block] = []
    prev_type = tokenize.NEWLINE
    try:
        tokens = list(tokenize.generate_tokens(io.StringIO(src).readline))
    except (tokenize.TokenError, SyntaxError, IndentationError):
        return hash_blocks(src)  # unparseable: fall back to plain # comments
    for tok in tokens:
        if tok.type == tokenize.COMMENT:
            start = tok.start[0]
            prev = blocks[-1] if blocks else None
            if prev and not prev.doc and prev.start + len(prev.lines) == start:
                prev.lines += strip_markers(tok.string)
            else:
                blocks.append(Block(start, strip_markers(tok.string), False, ""))
        elif (tok.type == tokenize.STRING and prev_type in (tokenize.NEWLINE, tokenize.INDENT, tokenize.DEDENT, tokenize.NL, tokenize.ENCODING)
              and re.match(r"^[rRuU]?(\"\"\"|''')", tok.string)):
            body = re.sub(r"^[rRuU]?(\"\"\"|''')|(\"\"\"|''')$", "", tok.string)
            decl = next((lines[i].strip() for i in range(tok.start[0] - 2, max(tok.start[0] - 22, -1), -1)
                         if re.match(r"^\s*(?:async\s+def|def|class)\s", lines[i])), "")
            blocks.append(Block(tok.start[0], body.split("\n"), True, decl))
        if tok.type not in (tokenize.COMMENT, tokenize.NL):
            prev_type = tok.type
    return blocks


def strings_prose(src: str, ext: str) -> list[str]:
    """User-facing text of a resource file, on its own line numbers; keys and placeholders masked."""
    prose = [""] * (src.count("\n") + 1)
    for m in STRING_VALUE[ext].finditer(src):
        if m.groupdict().get("k", "").startswith("@"):
            continue  # .arb metadata
        line = src.count("\n", 0, m.start("v"))
        text = PLACEHOLDER.sub(" ", m.group("v"))
        prose[line] = (prose[line] + " " + text).strip()
    return prose


def locale_from_path(path: str, known: list[str]) -> list[str] | None:
    """fr-CA/nav.json, messages.fr.resx, fr.lproj -> the matching locale tag, if we ship one."""
    for m in LOCALE_IN_PATH.finditer(path):
        lang, region = m.group(1), m.group(2)
        tag = f"{lang}-{region.upper()}" if region else lang
        if tag in known:
            return [tag]
        if lang in known:
            return [lang]
    return None


def blocks_for(src: str, ext: str) -> list[Block]:
    if ext in PYTHON:
        return py_blocks(src)
    if ext in HASH_FAMILY:
        return hash_blocks(src)
    return c_blocks(src, ext)


# ---- masking doc syntax ------------------------------------------------------

def mask_doc(text: str) -> str:
    """Blank out doc syntax so only prose reaches the prose checks. Keeps newlines."""
    blank = lambda m: re.sub(r"[^\n]", " ", m.group())  # noqa: E731
    rules = [
        (r"<code>.*?</code>|<example>.*?</example>|```.*?```", re.S),
        (r"(?m)^\s*@example\b[^@]*", re.S),                         # JSDoc example bodies
        (r"(?m)^\s*(?:>>>|\.\.\.)\s.*$", 0),                           # doctest
        (r"\{@\w+[^}]*\}", 0),                                          # {@link Foo}
        (rf"@{TAG_WITH_NAME}\b\s*(?:\{{[^}}]*\}}\s*)?[\w.$\[\]=]*\s*-?", re.I),
        (r"@\w+\s*(?:\{[^}]*\})?(?:\s*\[[^\]]*\])?", 0),                 # other tags, types, YARD [Type]
        (r"(?m)^\s*-\s*(?:Parameters?(?:\s+\w+)?|Returns|Throws|Note|Warning|Precondition|Complexity)\s*:", 0),  # Swift
        (r"<(?:see|seealso|paramref|typeparamref|inheritdoc|autogeneratedoc)\b[^>]*/?>", 0),
        (r"</?\w+(?:\s+\w+=\"[^\"]*\")*\s*/?>", 0),                    # remaining XML tags
        (r"(?m):(?:param|type|raises|var|ivar|cvar)\s+[^:]*:|:r?type:|:returns?:", 0),
        (r"(?m)^\s*(?:Args|Arguments|Parameters|Returns|Yields|Raises|Examples?|Attributes|Notes?|See Also|Throws|Errors|Panics|Safety)\s*:?\s*$", 0),
        (r"(?m)^\s*-{3,}\s*$", 0),                                      # numpy underlines
        (r"(?m)^\s*\*?\w+\*?\s*(?:\([^)]*\))?\s*:(?=\s)", 0),           # Google "name (type):"
        (r"(?m)^\s*#\s*(?:Examples?|Errors|Panics|Safety|Arguments|Returns)\s*$", 0),  # rustdoc sections
    ]
    for pat, flags in rules:
        text = re.sub(pat, blank, text, flags=flags)
    return text


def first_sentence(text: str) -> str:
    flat = " ".join(text.split())
    return re.split(r"(?<=[.!?])\s", flat, maxsplit=1)[0] if flat else ""


def echoes(description: str, ident_words: set[str]) -> bool:
    words = [stem(w.lower()) for w in re.findall(r"[A-Za-z]+", description)]
    content = [w for w in words if w not in FILLER_STEMS]
    return bool(words) and all(w in ident_words for w in content)


FILLER_STEMS = {stem(w) for w in FILLER}


# ---- doc checks --------------------------------------------------------------

PARAM_LINE = re.compile(
    rf"@{TAG_WITH_NAME}\s+(?:\{{[^}}]*\}}\s*)?\[?(\w+)[^\s]*\s*-?\s*(.*)"   # @param {T} name - desc
    r"|<param\s+name=\"(\w+)\">(.*?)</param>"                             # .NET
    r"|:param\s+(?:\w+\s+)?(\w+):\s*(.*)"                                 # reST
    r"|-\s*Parameter\s+(\w+):\s*(.*)"                                       # Swift
    r"|^\s*(\w+)\s*(?:\([^)]*\))?:\s+(.+)",                               # Google style
    re.I,
)
RETURNS_ECHO = re.compile(
    r"(?:@returns?\s*(?:\{[^}]*\}\s*)?|<returns>\s*|:returns?:\s*|^\s*Returns:\s*)"
    r"(?:the\s+)?(?:result|return value|value|returned value|output)\.?\s*(?:</returns>)?\s*$",
    re.I | re.M,
)
GENERATED = re.compile(
    r"<autogeneratedoc\s*/>|TODO:?\s*Edit XML Comment Template"          # GhostDoc
    r"|\b_(?:summary|extended_summary|description|type)_\b"               # autoDocstring
    r"|@param\s+\{\*\}"                                                  # Document This
    r"|^\s*@(?:param|arg)\s+[\w$]+\s*$|^\s*@returns?\s*$",                # empty IDE stub tags
    re.I | re.M,
)
THIS_METHOD = re.compile(
    r"\bthis (?:method|function|class|property|constructor|module|component|hook)\s+"
    r"(?:is used to|will|is responsible for|allows you to|helps(?: to)?|is designed to|serves to)\b"
    r"|\ban? (?:helper|utility|simple) (?:function|method|class) (?:that|to|for|which)\b",
    re.I,
)


def doc_hits(b: Block) -> list[dict]:
    hits = []
    raw = "\n".join(b.lines)

    def hit(offset_line: int, sev: str, cat: str, match: str) -> None:
        hits.append({"line": b.start + offset_line, "severity": sev, "category": cat, "match": match.strip()[:80]})

    for i, line in enumerate(b.lines):
        for rx, sev, cat in ((GENERATED, "hard", "generated-doc"), (THIS_METHOD, "soft", "this-method")):
            for m in rx.finditer(line):
                hit(i, sev, cat, m.group())
        if b.doc and RETURNS_ECHO.search(line):
            hit(i, "hard", "returns-echo", line)
        m = PARAM_LINE.search(line) if b.doc else None
        if m:
            name, desc = next((m.group(k), m.group(k + 1)) for k in (1, 3, 5, 7, 9) if m.group(k))
            if desc and echoes(re.sub(r"</?\w+[^>]*>", " ", desc), split_ident(name)):
                hit(i, "hard", "param-echo", line)
    if b.doc and b.decl:
        summary = first_sentence(mask_doc(raw))
        if summary and echoes(summary, split_ident(b.decl)):
            hit(0, "hard", "echo-doc", f"{summary} <- {b.decl[:40]}")
            hits[-1]["span"] = [b.start, b.start + len(b.lines) - 1]  # the whole block, for --diff
    return hits


REGISTER = None  # set from the config in main()
LENGTH_KEEP = 3  # per file; long comment sentences are common, so show the worst and count the rest


def cap_length(hits: list[dict]) -> list[dict]:
    longs = [h for h in hits if h["category"] == "ste-length"]
    if len(longs) <= LENGTH_KEEP:
        return hits
    words = lambda h: int(h["match"].split()[0])  # noqa: E731
    keep = sorted(longs, key=words, reverse=True)[:LENGTH_KEEP]
    rest = len(longs) - LENGTH_KEEP
    summary = {"line": keep[0]["line"], "severity": "soft", "category": "ste-length",
               "match": f"{rest} more sentences over 25 words in this file (--all lists them)"}
    return [h for h in hits if h["category"] != "ste-length"] + keep + [summary]


def fold_aliases(hits: list[dict]) -> list[dict]:
    """One glossary-alias line per alias and file, with a count, instead of one per use."""
    seen: dict[str, dict] = {}
    out = []
    for h in sorted(hits, key=lambda h: h["line"]):
        if h["category"] != "glossary-alias":
            out.append(h)
            continue
        key = h["match"].lower()
        if key in seen:
            seen[key]["count"] = seen[key].get("count", 1) + 1
        else:
            seen[key] = dict(h)
            out.append(seen[key])
    for h in seen.values():
        if h.get("count", 1) > 1:
            h["match"] += f" (x{h['count']}, first at L{h['line']})"
    return out


def condense(hits: list[dict]) -> list[dict]:
    return fold_aliases(cap_length(hits))


def gitlab_report(results: list[dict]) -> list[dict]:
    """GitLab Code Quality (Code Climate) issues: shown in the merge request widget."""
    import hashlib
    out, seen = [], collections.Counter()
    for h in results:
        base = f"{h['file']}|{h['category']}|{h['match']}"
        seen[base] += 1  # the same text twice in one file needs two fingerprints
        key = f"{base}|{seen[base]}".encode()
        out.append({
            "description": f"{h['category']}: {h['match']}",
            "check_name": f"ocre-jelly/{h['category']}",
            "fingerprint": hashlib.sha1(key).hexdigest(),  # line left out, so moving text keeps its identity
            "severity": "major" if h["severity"] == "hard" else "minor",
            "location": {"path": h["file"], "lines": {"begin": h["line"]}},
        })
    return out


def parse_diff(diff: str) -> dict[str, set[int]]:
    """Added line numbers per file, from a unified diff (git diff, git show, a PR's .diff)."""
    added: dict[str, set[int]] = {}
    path, line = None, 0
    for raw in diff.split("\n"):
        if raw.startswith("+++ "):
            name = raw[4:].split("\t")[0].strip().strip('"')
            path = None if name == "/dev/null" else (name[2:] if name[:2] in ("b/", "w/", "i/") else name)
            if path is not None:
                added.setdefault(path, set())
        elif raw.startswith("@@"):
            m = re.match(r"@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@", raw)
            line = int(m.group(1)) if m else 0
        elif path is None or raw.startswith(("--- ", "diff ", "index ", "\\")):
            continue
        elif raw.startswith("+"):
            added[path].add(line)
            line += 1
        elif raw.startswith(" ") or raw == "":
            line += 1
    return {p: lines for p, lines in added.items() if lines}


def scan_source(src: str, ext: str, aliases: dict[str, list[str]] | None = None, all_hits: bool = False,
                locales: list[str] | None = None, protected_terms: list[str] | None = None) -> list[dict]:
    ctx = "docs" if ext in PROSE else "strings" if ext in STRINGS else "comments"
    if ext in PROSE:
        hits = scan.scan(src, aliases=aliases, locales=locales, protected_terms=protected_terms, register=REGISTER, context=ctx)
        return sorted(hits if all_hits else condense(hits), key=lambda h: (h["line"], h["severity"]))
    if ext in STRINGS:  # each string is its own paragraph, so scan values one by one
        hits = []
        for n, value in enumerate(strings_prose(src, ext)):
            if value:
                hits += [{**h, "line": n + 1}
                         for h in scan.scan(value, aliases=aliases, locales=locales, protected_terms=protected_terms, register=REGISTER, context=ctx)]
        return sorted(hits if all_hits else condense(hits), key=lambda h: (h["line"], h["severity"]))
    blocks = blocks_for(src, ext)
    total = src.count("\n") + 1
    prose = [""] * total
    for b in blocks:
        masked = mask_doc("\n".join(b.lines)).split("\n")
        for i, text in enumerate(masked):
            if b.start - 1 + i < total:
                prose[b.start - 1 + i] = text
    hits = scan.scan("\n".join(prose), aliases=aliases, locales=locales, protected_terms=protected_terms, register=REGISTER, context=ctx)
    for b in blocks:
        hits += doc_hits(b)
    hits = scan.suppress(hits, src)  # markers in the raw source also cover doc-comment findings
    if not all_hits:
        hits = condense(hits)
    return sorted(hits, key=lambda h: (h["line"], h["severity"]))


# ---- code-unchanged check ----------------------------------------------------

def code_only(src: str, ext: str) -> str:
    """Source with every comment and docstring removed and whitespace collapsed."""
    if ext in PYTHON:
        try:
            out, prev = [], tokenize.NEWLINE
            for tok in tokenize.generate_tokens(io.StringIO(src).readline):
                is_doc = (tok.type == tokenize.STRING and prev in (tokenize.NEWLINE, tokenize.INDENT, tokenize.DEDENT, tokenize.NL)
                          and re.match(r"^[rRuU]?(\"\"\"|''')", tok.string))
                if tok.type not in (tokenize.COMMENT, tokenize.NL, tokenize.INDENT, tokenize.DEDENT) and not is_doc:
                    out.append(tok.string)
                if tok.type not in (tokenize.COMMENT, tokenize.NL):
                    prev = tok.type
            return " ".join(" ".join(out).split())
        except (tokenize.TokenError, SyntaxError, IndentationError):
            pass
    rx = HASH_TOKEN if ext in HASH_FAMILY else C_TOKEN
    stripped = rx.sub(lambda m: m.group() if m.lastgroup == "str" else " ", src)
    return " ".join(stripped.split())


COMMENT_START = re.compile(r"^\s*(?:$|//|/\*|\*|#|\"\"\"|''')")
TRIPLE = re.compile(r"^[rRuU]?(\"\"\"|''')")


def docstring_lines(src: str) -> set[int]:
    """0-based line numbers covered by Python docstrings (tokenize is exact here)."""
    lines, prev = set(), tokenize.NEWLINE
    try:
        for tok in tokenize.generate_tokens(io.StringIO(src).readline):
            if (tok.type == tokenize.STRING and TRIPLE.match(tok.string)
                    and prev in (tokenize.NEWLINE, tokenize.INDENT, tokenize.DEDENT, tokenize.NL)):
                lines.update(range(tok.start[0] - 1, tok.end[0]))
            if tok.type not in (tokenize.COMMENT, tokenize.NL):
                prev = tok.type
    except (tokenize.TokenError, SyntaxError, IndentationError):
        pass
    return lines


def code_prefix(line: str) -> str | None:
    """Code before a trailing comment, or None when the line has no comment marker."""
    m = re.search(r"\s(?://|#)", line)
    return line[:m.start()].rstrip() if m else None


def changed_code_lines(a: str, b: str, ext: str) -> str | None:
    """Independent line-level check: every changed line must be a comment, blank,
    or keep its code before a trailing comment. It doesn't trust the tokenizer,
    so a regex literal like /[/*]/ can't hide a code change from it."""
    la, lb = a.split("\n"), b.split("\n")
    doc_a, doc_b = (docstring_lines(a), docstring_lines(b)) if ext in PYTHON else (set(), set())
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, la, lb, autojunk=False).get_opcodes():
        if tag == "equal":
            continue
        bad_a = [i for i in range(i1, i2) if i not in doc_a and not COMMENT_START.match(la[i])]
        bad_b = [j for j in range(j1, j2) if j not in doc_b and not COMMENT_START.match(lb[j])]
        if not bad_a and not bad_b:
            continue
        if len(bad_a) == len(bad_b) and all(
                code_prefix(la[i]) is not None and code_prefix(la[i]) == code_prefix(lb[j])
                for i, j in zip(bad_a, bad_b)):
            continue  # only trailing comments changed
        i = bad_a[0] if bad_a else None
        text = la[i] if i is not None else lb[bad_b[0]]
        where = f"line {i + 1}" if i is not None else f"new line {bad_b[0] + 1}"
        return f"code changed at {where}: {text.strip()[:60]!r}"
    return None


def same_code(a: str, b: str, ext: str) -> str | None:
    """None only when both checks agree that only comments changed."""
    ca, cb = code_only(a, ext), code_only(b, ext)
    if ca != cb:
        i = next((k for k, (x, y) in enumerate(zip(ca, cb)) if x != y), min(len(ca), len(cb)))
        return f"code changed near: {ca[max(0, i - 30):i + 30]!r} -> {cb[max(0, i - 30):i + 30]!r}"
    return changed_code_lines(a, b, ext)


# ---- cli ---------------------------------------------------------------------

def selftest() -> None:
    cs = '''/// <summary>
/// Gets the name of the user.
/// </summary>
/// <param name="userId">The user identifier.</param>
/// <returns>The result.</returns>
/// <autogeneratedoc />
// TODO Edit XML Comment Template for GetUserName
public string GetUserName(int userId) => "";

/// <summary>Retries the call three times, then throws, so callers see one failure.</summary>
public void CallWithRetry() {}
'''
    cats = {h["category"] for h in scan_source(cs, ".cs")}
    assert {"echo-doc", "param-echo", "returns-echo", "generated-doc"} <= cats, cats
    assert not [h for h in scan_source(cs, ".cs") if h["line"] >= 10], "good doc flagged"

    ts = '''/**
 * This function is used to delve into the cache.
 * @param {string} key - The key.
 * @returns {number} Seconds until the entry expires, or -1 when it is missing.
 * @example
 * ttl("a") // Here's the thing
 */
export function ttl(key: string): number { const url = "http://x.io//not-a-comment"; return 0 }
'''
    hits = scan_source(ts, ".ts")
    cats = {h["category"] for h in hits}
    assert {"this-method", "ai-vocabulary", "param-echo"} <= cats, cats
    assert "throat-clearing" not in cats, "example code was scanned"
    assert "returns-echo" not in cats

    py = '''def get_user(user_id):
    """Get the user.

    Args:
        user_id (int): The user id.

    >>> get_user(1)  # let's dive in
    """
    return None  # A helper function that fetches it
'''
    cats = {h["category"] for h in scan_source(py, ".py")}
    assert {"echo-doc", "param-echo", "this-method"} <= cats, cats
    assert "throat-clearing" not in cats

    stubs = '"""_summary_\n\n    Args:\n        x (_type_): _description_\n    """'
    assert "generated-doc" in {h["category"] for h in scan_source("def f(x):\n    " + stubs + "\n    return x\n", ".py")}
    assert "generated-doc" in {h["category"] for h in scan_source("/**\n * @param {*} a\n * @returns\n */\nfunction f(a) {}\n", ".js")}
    swift = "/// Loads the cache from disk.\n/// - Parameter path: The path.\nfunc load(path: String) {}\n"
    assert "param-echo" in {h["category"] for h in scan_source(swift, ".swift")}, scan_source(swift, ".swift")

    wordy = "".join(f"// {' '.join(['w'] * (30 + k))}.\nint v{k};\n" for k in range(6))
    capped = [h for h in scan_source(wordy, ".c") if h["category"] == "ste-length"]
    assert len(capped) == 4 and sum("3 more" in h["match"] for h in capped) == 1, capped
    assert len([h for h in scan_source(wordy, ".c", all_hits=True) if h["category"] == "ste-length"]) == 6

    fr_json = '{\n  "title": "Il est important de noter que {{count}} e-mails partent",\n  "ok": "Enregistrer"\n}\n'
    hits = scan_source(fr_json, ".json", locales=["fr-CA"])
    assert {(h["line"], h["category"]) for h in hits} >= {(2, "throat-clearing"), (2, "locale-term")}, hits
    assert not [h for h in hits if "count" in h["match"]], "placeholder scanned"
    assert locale_from_path("src/i18n/locales/fr-CA/nav.json", ["en", "fr", "fr-CA"]) == ["fr-CA"]
    assert locale_from_path("Resources/Strings.fr.resx", ["en", "fr", "fr-CA"]) == ["fr"]
    assert locale_from_path("src/components/Button.json", ["en", "fr"]) is None
    po = 'msgid "Save"\nmsgstr "Plongeons dans la sauvegarde"\n'
    assert "throat-clearing" in {h["category"] for h in scan_source(po, ".po", locales=["fr"])}

    folded = fold_aliases([{"line": n, "severity": "soft", "category": "glossary-alias", "match": "ligne -> Item"} for n in (4, 9, 2)])
    assert len(folded) == 1 and folded[0]["match"] == "ligne -> Item (x3, first at L2)", folded

    diff = (
        "diff --git a/docs/a.md b/docs/a.md\n--- a/docs/a.md\n+++ b/docs/a.md\n@@ -1,3 +1,4 @@\n"
        " keep\n-old line\n+Here's the thing: new\n+second new\n unchanged\n\\ No newline at end of file\n"
        "diff --git a/gone.md b/gone.md\n--- a/gone.md\n+++ /dev/null\n@@ -1 +0,0 @@\n-bye\n"
        "diff --git a/n.ts b/n.ts\nnew file mode 100644\n--- /dev/null\n+++ b/n.ts\n@@ -0,0 +1,2 @@\n+// x\n+const y = 1\n"
        "diff --git a/old.md b/new name.md\nrename from old.md\n--- a/old.md\n+++ \"b/new name.md\"\n@@ -5,2 +7,3 @@\n ctx\n+added\n ctx\n"
    )
    assert parse_diff(diff) == {"docs/a.md": {2, 3}, "n.ts": {1, 2}, "new name.md": {8}}, parse_diff(diff)
    md = "Clean line.\nHere's the thing: added.\nLet's dive in, old text.\n"
    block = [h for h in scan_source("/**\n * Gets the user.\n * More.\n */\nfunction getUser() {}\n", ".ts") if h["category"] == "echo-doc"]
    assert block and block[0]["span"] == [1, 4], block
    kept = [h for h in scan_source(md, ".md", all_hits=True) if h["line"] in {2}]
    assert [h["category"] for h in kept] == ["throat-clearing"], kept

    quiet = "// ocre-jelly: ignore echo-doc\n/** Gets the user. */\nfunction getUser() {}\n"
    assert not [h for h in scan_source(quiet, ".ts") if h["category"] == "echo-doc"], "suppression ignored in code"

    rep_ = gitlab_report([{"file": "docs/a.md", "line": 3, "severity": "hard", "category": "throat-clearing", "match": "x"}])
    assert rep_[0]["severity"] == "major" and rep_[0]["location"] == {"path": "docs/a.md", "lines": {"begin": 3}}
    assert rep_[0]["check_name"] == "ocre-jelly/throat-clearing" and len(rep_[0]["fingerprint"]) == 40
    twice = gitlab_report([{"file": "a.md", "line": n, "severity": "soft", "category": "em-dash", "match": "x"} for n in (1, 9)])
    assert twice[0]["fingerprint"] != twice[1]["fingerprint"], "duplicate fingerprints"

    go = "// Parse parses.\nfunc Parse() {}\n"
    assert [h["category"] for h in scan_source(go, ".go")] == ["echo-doc"]

    assert same_code(ts, ts.replace("This function is used to delve into", "Reads"), ".ts") is None
    assert same_code(ts, ts.replace("return 0", "return 1"), ".ts")
    assert same_code(py, py.replace("Get the user.", "Load one user by id."), ".py") is None
    tricky = "const pattern = /[/*]/;\nfunction f() {\n  return 1\n}\n/* trailing */\n"
    assert same_code(tricky, tricky.replace("return 1", "return 999999"), ".ts"), "regex literal hid a code change"
    assert same_code(tricky, tricky.replace("trailing", "why it trails"), ".ts") is None
    inline = "x = compute()  # slow path\n"
    assert same_code(inline, inline.replace("slow path", "cached after first call"), ".py") is None
    assert same_code(inline, inline.replace("compute()", "compute(1)"), ".py")
    multi = "/**\n * Old summary.\n */\nint f();\n"
    assert same_code(multi, multi.replace(" * Old summary.", " * New summary.\n * With a second line."), ".c") is None
    assert same_code(py, py.replace("return None", "return 1"), ".py")
    print("selftest ok")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("files", nargs="*")
    ap.add_argument("--lang", help="extension for stdin input, e.g. .ts")
    ap.add_argument("--glossary", metavar="MD")
    ap.add_argument("--locale", help="comma list, e.g. en-CA,fr-CA; a locale in a resource file's path wins")
    ap.add_argument("--no-config", action="store_true", help="ignore the layered ocre-jelly JSON config")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--format", choices=("text", "json", "gitlab"), default=None,
                    help="gitlab: a Code Quality report for the merge request widget")
    ap.add_argument("--fail-on", choices=("hard", "soft"), help="exit 1 when a finding of this severity or higher remains")
    ap.add_argument("--all", action="store_true", help="list every long sentence and every alias use, not a summary")
    ap.add_argument("--same-code", nargs=2, metavar=("ORIGINAL", "REWRITTEN"))
    ap.add_argument("--diff", action="store_true",
                    help="read a unified diff on stdin; report only findings on added lines (prose files included)")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return selftest()
    if args.same_code:
        a, b = (Path(p) for p in args.same_code)
        problem = same_code(a.read_text(encoding="utf-8"), b.read_text(encoding="utf-8"), a.suffix.lower())
        if not args.no_config:
            import telemetry
            telemetry.record("gate", gate="same-code", ok=problem is None, ext={a.suffix.lower() or "(none)": 1})
        print(problem or "code unchanged")
        sys.exit(1 if problem else 0)

    global LENGTH_KEEP, REGISTER
    cfg = scan.load_settings(args.no_config)
    REGISTER = cfg.get("register")
    if not args.no_config:
        LENGTH_KEEP = cfg["thresholds"]["length_hits_per_file"]
    aliases = {}
    glossary = args.glossary or scan.default_glossary(cfg)
    if glossary:
        with open(glossary, encoding="utf-8") as f:
            aliases = scan.load_glossary(scan.read_capped(f))
    files = args.files
    only: dict[str, set[int]] = {}  # --diff: file -> added lines
    if args.diff:
        root = Path(cfg.get("_root") or Path.cwd())
        supported = C_FAMILY | HASH_FAMILY | PYTHON | STRINGS | PROSE
        for rel, lines in parse_diff(scan.read_capped(sys.stdin)).items():
            full = root / rel
            if Path(rel).suffix.lower() in supported and full.is_file() and root.resolve() in full.resolve().parents:
                only[str(full)] = lines
        files = args.files = list(only)
        if not files:
            return print("-- no added lines in supported files")
    if cfg.get("_root") and cfg.get("ignore_paths"):
        import config
        files = [f for f in files if not config.ignored(f, Path(cfg["_root"]), cfg["ignore_paths"])]
        if len(files) < len(args.files):
            print(f"-- skipped {len(args.files) - len(files)} file(s) matching ignore_paths", file=sys.stderr)
    started = time.perf_counter()
    sources = [(p, Path(p).suffix.lower()) for p in files] or [("<stdin>", (args.lang or ".js").lower())]
    results = []
    for name, ext in sources:
        if name == "<stdin>":
            src = scan.read_capped(sys.stdin)
        else:
            with open(name, encoding="utf-8") as f:
                src = scan.read_capped(f)
        locales = scan.parse_locales(args.locale) or cfg["locales"] or None
        if ext in STRINGS:
            locales = locale_from_path(name, scan.available_locales()) or locales
        if name in only:  # scan the whole file for context, keep what the diff added
            lines = only[name]
            hits = [h for h in scan_source(src, ext, aliases, True, locales, cfg["protected_terms"])
                    if h["line"] in lines or ("span" in h and any(h["span"][0] <= n <= h["span"][1] for n in lines))]
            hits = hits if args.all else condense(hits)
            name = str(Path(name).relative_to(Path(cfg.get("_root") or Path.cwd())))
        else:
            hits = scan_source(src, ext, aliases, args.all, locales, cfg["protected_terms"])
        results += [{**h, "file": name} for h in hits]
    if cfg["severity"]:
        import config
        results = config.apply_severity(results, cfg["severity"])
    if not args.no_config:
        import telemetry
        telemetry.record("codedoc", started, results, locales=cfg["locales"] or None,
                         ext=telemetry.extensions([n if n != "<stdin>" else f"x{e}" for n, e in sources]),
                         files=len(sources), skipped=len(args.files) - len(files))
    fmt = args.format or ("json" if args.json else "text")
    failing = {"hard": {"hard"}, "soft": {"hard", "soft"}}.get(args.fail_on or "", set())
    code = 1 if any(h["severity"] in failing for h in results) else 0
    if fmt == "gitlab":
        print(json.dumps(gitlab_report(results), indent=2, ensure_ascii=False))
        sys.exit(code)
    if fmt == "json":
        print(json.dumps(results, indent=2))
        sys.exit(code)
    multi = len(sources) > 1
    for h in results:
        where = f"{h['file']}:L{h['line']}" if multi else f"L{h['line']}"
        print(f"{where:<6} {h['severity']:<4} {h['category']:<22} {h['match']!r}")
    hard = sum(h["severity"] == "hard" for h in results)
    print(f"-- {len(results)} candidates ({hard} hard). Candidates only; confirm in context.")
    sys.exit(code)


if __name__ == "__main__":
    try:
        main()
    except ValueError as e:  # bad locale tag or glossary: a clear message, not a traceback
        scan._record_error(e)
        sys.exit(f"{Path(__file__).name}: {e}")
    except Exception as e:
        scan._record_error(e)
        raise
