#!/usr/bin/env python3
"""Generate the reference pages that list modules, locales and checks.

These three pages come from the code, so they can't drift from it:
  docs/reference/modules.md   from modules/*.md frontmatter
  docs/reference/locales.md   from locales/*.py
  docs/reference/checks.md    from locale patterns plus the scanner's built-in checks

Usage:
  gen_docs.py            write the pages
  gen_docs.py --check    exit 1 if a page is out of date (setup.sh --check runs this)
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import modules as M  # noqa: E402
import scan as S  # noqa: E402

REPO = HERE.parent.parent.parent
DOCS = REPO / "docs" / "reference"
HEADER = "<!-- Generated by skills/ocre-jelly/scripts/gen_docs.py. Don't edit; run it instead. -->\n\n"

# What each check means. Categories come from the code; a missing entry fails the build.
CHECKS = {
    "throat-clearing": ("Openers that delay the point", "\"Here's the thing:\", \"Let's dive in\", « Il est important de noter que »"),
    "emphasis-crutch": ("Phrases that manufacture importance", "\"Let that sink in\", \"Full stop.\", « Point final. »"),
    "chatbot-artifact": ("Chat-assistant leftovers", "\"I hope this helps\", \"Great question\", « N'hésitez pas à »"),
    "cutoff-disclaimer": ("Model self-reference", "\"As of my last update\", \"As an AI language model, I\""),
    "reasoning-artifact": ("Visible chain-of-thought scaffolding", "\"Let me think step by step\""),
    "significance-inflation": ("Inflated importance", "\"stands as a testament\", \"pivotal moment\", « change la donne »"),
    "generic-conclusion": ("Empty closing lines", "\"The future looks bright\", « Seul l'avenir nous le dira »"),
    "ai-vocabulary": ("Words models overuse", "\"delve\", \"tapestry\", \"multifaceted\", « tapisserie »"),
    "binary-contrast": ("\"It's not X, it's Y\" drama", "\"It's not just a tool. It's a revolution.\", « Ce n'est pas X, c'est Y »"),
    "ing-tail": ("Trailing participle that adds nothing", "\", highlighting…\", \", showcasing…\", « , soulignant… »"),
    "vague-attribution": ("Claims with no source", "\"Experts argue\", \"Studies show\", « De nombreuses études »"),
    "copula-avoidance": ("\"serves as\" instead of \"is\"", "\"serves as a\", « joue un rôle clé »"),
    "promotional": ("Marketing adjectives", "\"world-class\", \"seamless\", « de pointe », « incontournable »"),
    "filler-adverb": ("Sentence-initial filler", "\"Importantly,\", \"Crucially,\", « Notamment, »"),
    "reader-steering": ("Telling the reader what to think", "\"Here's why\", \"Why this matters\", « Voici pourquoi »"),
    "colon-reveal": ("Drumroll colons", "\"The key is:\", « La clé est : »"),
    "false-range": ("\"from X to Y, from A to B\" ranges", "\"spanning everything from\""),
    "list-inflation": ("Listicle framing", "\"Here are 5 reasons\", « Voici 5 astuces »"),
    "fragmentation": ("Dramatic fragments", "\". That's it.\""),
    "recap-coda": ("Closing recap paragraph", "« En résumé, », « Pour conclure, »"),
    "ste-wordy": ("Wordy phrasing STE replaces with one word", "\"in order to\", \"utilize\", « afin de », « procéder à »"),
    "ste-length": ("Sentence longer than `thresholds.sentence_words`", "any sentence over 25 words"),
    "em-dash": ("Em-dash habit (`thresholds.em_dash_per_paragraph` or more in one paragraph)", "three — in one paragraph"),
    "glossary-alias": ("An alias to avoid from the ubiquitous-language glossary", "\"basket\" when the Term is Order"),
    "locale-spelling": ("Spelling from another variety of English", "\"colour\" in en-US, \"color\" in en-GB"),
    "locale-term": ("A term the locale replaces", "\"e-mail\" in fr-CA (courriel), \"hashtag\" in fr-FR (mot-dièse)"),
    "anglicism": ("Anglicism the OQLF advises against (fr-CA)", "« céduler », « faire du sens », « à l'effet que »"),
    "typography": ("Missing no-break space before ; : ! ? (fr-FR, fr-BE)", "« Attention: »"),
    "echo-doc": ("Doc summary that only restates the declaration", "\"Gets the user name.\" on GetUserName"),
    "param-echo": ("Parameter description that only restates the name", "\"@param id The id.\""),
    "returns-echo": ("Return description with no content", "\"@returns The result.\""),
    "generated-doc": ("Doc-generator placeholders", "`<autogeneratedoc />`, `_summary_`, `@param {*} x`"),
    "this-method": ("\"This method is used to…\" openers", "\"A helper function that…\""),
}
BUILTIN = {"ste-length": "soft", "em-dash": "soft", "glossary-alias": "soft"}
CODEDOC = {"echo-doc": "hard", "param-echo": "hard", "returns-echo": "hard", "generated-doc": "hard", "this-method": "soft"}


def md_cell(text: str) -> str:
    return text.replace("|", "\\|")


def modules_page() -> str:
    mods = M.all_modules()
    rows = ["| Module | Kind | Default | Turns on when (auto) | Read when / writes | Summary |", "|---|---|---|---|---|---|"]
    for name, m in mods.items():
        detect = ", ".join(f"`{d}`" for d in m["detect"] + m["detect_files"]) or "—"
        use = f"writes `{m['target']}`" if m["kind"] == "export" else m.get("when", "")
        rows.append(f"| [`{name}`](../../skills/ocre-jelly/modules/{name}.md) | {m['kind']} | {m['default']} | "
                    f"{md_cell(detect) if m['default'] == 'auto' else '—'} | {md_cell(use)} | {md_cell(m.get('description', ''))} |")
    counts = {k: sum(m["kind"] == k for m in mods.values()) for k in ("rules", "export")}
    return (HEADER + "# Modules\n\n"
            f"{len(mods)} modules: {counts['rules']} rules modules and {counts['export']} export modules. "
            "Turn one on or off with `modules.py enable|disable <name> [--project|--local]`, or set it in the "
            "`modules` map of the [configuration](configuration.md). `modules.py list` shows the state of each one in the current repo, and why.\n\n"
            "- **rules** modules add one index line to the session. The agent reads the module file when the work matches its trigger.\n"
            "- **export** modules write a file for another tool when you run `modules.py export`.\n"
            "- **auto** means on when a named plugin is installed or a listed file exists at the repo root or one folder down.\n\n"
            + "\n".join(rows) + "\n")


def locales_page() -> str:
    rows = ["| Tag | Extends | Summary | Spelling classes | Preferred terms | Extra checks |", "|---|---|---|---|---|---|"]
    for tag in S.available_locales():
        ns = S.load_locale(tag)
        style = ", ".join(f"{k}: {v}" for k, v in ns.get("SPELLING_STYLE", {}).items()) or "—"
        prefer = len(ns.get("PREFER", {}))
        extra = ", ".join(sorted({*ns.get("SOFT", {}), *ns.get("HARD", {})})) if "PARENT" in ns else "base patterns"
        rows.append(f"| `{tag}` | {ns.get('PARENT', '—')} | {md_cell(ns.get('SUMMARY', ''))} | {style} | "
                    f"{prefer or '—'} | {md_cell(extra or '—')} |")
    return (HEADER + "# Locales\n\n"
            "Set them in the `locales` list of the [configuration](configuration.md), for example `[\"en-CA\", \"fr-CA\"]`. "
            "The scanners pick the locale per paragraph from its language, and per file for resource paths such as `fr-CA/nav.json` or `Strings.fr.resx`. "
            "A regional tag without its own file (for example `en-NZ`) uses its language's patterns only.\n\n"
            "Spelling classes for English: `our` (colour/color), `re` (centre/center), `ise` (organise/organize), `ll` (travelled/traveled), "
            "`misc` (grey/gray, defence/defense, catalogue/catalog, …). `gb` or `us` says which side the locale prefers.\n\n"
            + "\n".join(rows) + "\n")


def checks_page() -> str:
    found: dict[str, dict[str, set[str]]] = {}
    for tag in S.available_locales():
        for sev, cat, _rx, _s in S.locale_patterns(tag):
            entry = found.setdefault(cat, {"sev": set(), "lang": set()})
            entry["sev"].add(sev)
            entry["lang"].add(tag.split("-")[0])
    for cat, sev in {**BUILTIN, **CODEDOC}.items():
        found.setdefault(cat, {"sev": {sev}, "lang": {"all"}})
    missing = sorted(set(found) - set(CHECKS))
    if missing:
        sys.exit(f"gen_docs.py: describe these new check categories in CHECKS: {', '.join(missing)}")
    rows = ["| Category | Severity | Languages | Scanner | What it flags | Examples |", "|---|---|---|---|---|---|"]
    for cat in CHECKS:
        if cat not in found:
            continue
        info = found[cat]
        where = "codedoc.py" if cat in CODEDOC else "scan.py, codedoc.py"
        rows.append(f"| `{cat}` | {'/'.join(sorted(info['sev']))} | {', '.join(sorted(info['lang']))} | {where} | "
                    f"{md_cell(CHECKS[cat][0])} | {md_cell(CHECKS[cat][1])} |")
    return (HEADER + "# Checks\n\n"
            "Every finding has a category and a severity. **hard** means almost always a defect outside quotes. "
            "**soft** means a candidate that the agent confirms in context. A scanner hit is never a verdict by itself: "
            "see [the standards](../explanation/standards.md). Change a category's severity, or turn it off, with the `severity` map "
            "of the [configuration](configuration.md).\n\n"
            + "\n".join(rows) + "\n")


PAGES = {"modules.md": modules_page, "locales.md": locales_page, "checks.md": checks_page}


def main() -> None:
    check = "--check" in sys.argv[1:]
    stale = []
    for name, build in PAGES.items():
        path = DOCS / name
        content = build()
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote docs/reference/{name}")
    if stale:
        sys.exit(f"out of date: {', '.join(stale)}. Run skills/ocre-jelly/scripts/gen_docs.py")
    if check:
        print("docs ok")


if __name__ == "__main__":
    main()
