#!/usr/bin/env python3
"""ocre-jelly module manager.

A module is ../modules/<name>.md: simple `key: value` frontmatter plus a body.

  kind: rules    The body is added to the always-on rules (session and subagent
                 hooks) while the module is on.
  kind: export   The body is a template for one file that `export` writes into
                 the project. {{rules}} expands to core rules + active rules
                 modules. An optional <name>.py next to it with
                 render(ctx) -> str replaces the template.
  default: on | off | auto    auto = on when a plugin named in `detect:` is installed,
                              or a `detect_files:` glob matches in the project root
                              (at most one directory deep, no `**`)
  when:    trigger           rules only: the index line that tells the agent when to read it
  inject:  always            rules only: inline the whole body every session, not an index line
  target:  path              export only, relative to the project root
  write:   file | block      export only: own the whole file, or upsert a marked block
  needs:   glossary          export only: requires the project's ubiquitous language

State lives in the layered JSON config (see config.py): ~/.claude/ocre-jelly.json,
<repo>/.claude/ocre-jelly.json (committed), <repo>/.claude/ocre-jelly.local.json
(personal). Module states are its "modules" map: on, off or auto.

Usage:
  modules.py list
  modules.py enable|disable|reset NAME [--project|--local]
  modules.py config show|path|init|set [KEY VALUE] [--project|--local]
  modules.py rules
  modules.py export [NAME ...] [--glossary PATH] [--dry-run] [--force]
  modules.py hook session-start|subagent-start      (hook JSON on stdin)
  modules.py --selftest

Security posture: stdlib only, no network, no subprocess. Reads the module
folder, the two state files, the installed-plugins registry and the glossary.
Writes only the state files and export targets inside the project root, and
never overwrites a file that ocre-jelly did not generate unless --force.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import sys

sys.dont_write_bytecode = True  # keep the installed plugin folder clean
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL_DIR = HERE.parent
MODULES_DIR = SKILL_DIR / "modules"
CORE_RULES = SKILL_DIR / "core-rules.md"
MARK = "Generated by ocre-jelly"
BLOCK_START, BLOCK_END = "<!-- ocre-jelly:start -->", "<!-- ocre-jelly:end -->"
NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,40}$")

sys.path.insert(0, str(HERE))
import config  # noqa: E402
import scan  # noqa: E402


# ---- discovery -------------------------------------------------------------

def parse_module(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    meta, body = {}, text
    if text.startswith("---\n"):
        head, _, body = text[4:].partition("\n---\n")
        for line in head.splitlines():
            key, sep, value = line.partition(":")
            if sep:
                meta[key.strip()] = value.strip()
    meta.setdefault("kind", "rules")
    meta.setdefault("default", "off")
    meta["name"] = path.stem
    meta["body"] = body.strip()
    for key in ("detect", "detect_files"):
        meta[key] = [d.strip() for d in meta.get(key, "").split(",") if d.strip()]
    return meta


def all_modules(modules_dir: Path = MODULES_DIR) -> dict[str, dict]:
    mods = {}
    for path in sorted(modules_dir.glob("*.md")):
        if NAME_RE.match(path.stem):
            mods[path.stem] = parse_module(path)
    return mods


def installed_plugins() -> set[str]:
    try:
        data = json.loads((config.claude_dir() / "plugins" / "installed_plugins.json").read_text(encoding="utf-8"))
        return {key.split("@")[0] for key in data.get("plugins", {})}
    except (OSError, ValueError, AttributeError):
        return set()


def files_found(root: Path, patterns: list[str]) -> list[str]:
    # ponytail: shallow globs only, so a big repo never slows session start
    return [pat for pat in patterns
            if "**" not in pat and pat.count("/") <= 1 and next(root.glob(pat), None) is not None]


# ---- state -----------------------------------------------------------------
# All state lives in the layered JSON config (config.py). Module states are its "modules" map.

def resolve(mods: dict[str, dict], root: Path, plugins: set[str]) -> dict[str, tuple[bool, str]]:
    """name -> (active, why). local beats project beats user beats the module default."""
    layers = config.module_layers(root)
    out = {}
    for name, m in mods.items():
        state, src = m["default"], "default"
        for layer, states in layers:
            if states.get(name) in config.STATES:
                state, src = states[name], layer
        if state == "auto":
            found = [d for d in m["detect"] if d in plugins] + files_found(root, m["detect_files"])
            out[name] = (bool(found), f"{src}:auto ({', '.join(found) or 'not found'})")
        else:
            out[name] = (state == "on", src)
    return out


def set_state(name: str, state: str, layer: str, root: Path, mods: dict[str, dict]) -> Path:
    if name not in mods:
        sys.exit(f"unknown module: {name}. Run `modules.py list`.")

    def change(data: dict) -> None:
        states = data.setdefault("modules", {})
        if state == "reset":
            states.pop(name, None)
        else:
            states[name] = state
    return config.update_layer(layer, root, change)


# ---- rules -----------------------------------------------------------------

def locale_line(tags: list[str]) -> str:
    """One line naming the configured locales and each language's prose authority."""
    if not tags:
        return ""
    parts, langs = [], []
    for tag in tags:
        try:
            summary = scan.load_locale(tag).get("SUMMARY") or scan.load_locale(tag.split("-")[0]).get("SUMMARY", "")
        except ValueError as e:
            summary = f"unknown ({e})"
        parts.append(summary if summary.startswith(f"{tag}:") else f"{tag}: {summary}")
        langs.append(tag.split("-")[0])
    authorities = {lang: scan.load_locale(lang).get("AUTHORITY") for lang in dict.fromkeys(langs)}
    auth = ", ".join(f"{lang} -> `{SKILL_DIR / path}`" for lang, path in authorities.items() if path)
    return "Locales: " + " | ".join(parts) + (f"\nProse authority per language: {auth}" if auth else "")


def rules_text(mods: dict[str, dict], active: dict[str, tuple[bool, str]], full: bool = False,
               locales: list[str] | None = None) -> str:
    """Core rules, the locale line, then active rules modules.

    Progressive disclosure: by default a module contributes one index line (its
    `when:` trigger and file). The agent reads the file only when the work
    matches. `inject: always` modules, and full=True (exports for other agents,
    which can't read this machine's plugin folder), inline the whole body.
    """
    parts = [CORE_RULES.read_text(encoding="utf-8").strip()]
    if locales:
        parts.append(locale_line(locales))
    index = []
    for name, m in mods.items():
        if m["kind"] != "rules" or not active[name][0] or not m["body"]:
            continue
        if full or m.get("inject") == "always":
            parts.append(m["body"])
        else:
            index.append(f"- {name}: {m.get('when') or m.get('description', '')}")
    if index:
        parts.append(f"Active modules. Before work that matches one, read `{MODULES_DIR}/<name>.md`:\n" + "\n".join(index))
    return "\n\n".join(parts) + "\n"


def session_rules(root: Path, cfg: dict, full: bool = False) -> str:
    mods = all_modules()
    return rules_text(mods, resolve(mods, root, installed_plugins()), full or cfg["inject"] == "full", cfg["locales"])


def run_hook(event: str) -> None:
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except ValueError:
        payload = {}
    root = config.project_root(Path(payload["cwd"]) if payload.get("cwd") else None)
    cfg = config.load(root)
    if not cfg["enabled"]:
        return
    if event == "subagent-start":
        if not cfg["subagents"].get("inject", True):
            return
        matcher = cfg["subagents"].get("matcher")
        agent = str(payload.get("agent_type") or "")
        try:
            if matcher and agent and not re.search(matcher, agent, re.I):
                return
        except re.error:
            pass  # a bad regex fails open, like ponytail
    text = session_rules(root, cfg)
    if event == "subagent-start":  # SubagentStart drops raw stdout; it needs this JSON form
        print(json.dumps({"hookSpecificOutput": {"hookEventName": "SubagentStart", "additionalContext": text}}))
    else:
        sys.stdout.write(text)


# ---- export ----------------------------------------------------------------

def safe_target(root: Path, target: str) -> Path:
    path = (root / target).resolve()
    if not target or Path(target).is_absolute() or root.resolve() not in path.parents:
        raise ValueError(f"export target escapes the project root: {target!r}")
    return path


def render(m: dict, ctx: dict, modules_dir: Path = MODULES_DIR) -> str:
    code = modules_dir / f"{m['name']}.py"
    if code.exists():
        spec = importlib.util.spec_from_file_location(f"ocre_jelly_{m['name'].replace('-', '_')}", code)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod.render(ctx)
    return m["body"].replace("{{rules}}", ctx["rules"].strip()) + "\n"


def upsert_block(existing: str, content: str) -> str:
    block = f"{BLOCK_START}\n<!-- {MARK}. Edit ocre-jelly, then re-export. -->\n{content.strip()}\n{BLOCK_END}\n"
    if BLOCK_START in existing and BLOCK_END in existing:
        head, _, rest = existing.partition(BLOCK_START)
        _, _, tail = rest.partition(BLOCK_END)
        return head + block.rstrip("\n") + tail
    return (existing.rstrip("\n") + "\n\n" if existing.strip() else "") + block


def export_one(m: dict, root: Path, ctx: dict, dry_run: bool, force: bool) -> str:
    root = root.resolve()
    path = safe_target(root, m.get("target", ""))
    content = render(m, ctx)
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if m.get("write") == "block":
        new = upsert_block(old, content)
    else:
        if old and MARK not in old and not force:
            return f"skip  {m['name']}: {path.relative_to(root)} exists and was not generated by ocre-jelly (use --force)"
        new = content
    if new == old:
        return f"same  {m['name']}: {path.relative_to(root)}"
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new, encoding="utf-8")
    return f"{'would write' if dry_run else 'wrote'} {m['name']}: {path.relative_to(root)}"


def run_export(names: list[str], glossary: str | None, dry_run: bool, force: bool) -> None:
    root = config.project_root()
    cfg = config.load(root)
    mods = all_modules()
    active = resolve(mods, root, installed_plugins())
    exports = {n: m for n, m in mods.items() if m["kind"] == "export"}
    for n in names:
        if n not in exports:
            sys.exit(f"not an export module: {n}. Available: {', '.join(exports)}")
    chosen = names or [n for n in exports if active[n][0]]
    if not chosen:
        sys.exit("no export modules enabled. Enable one with `modules.py enable <name>` or name it.")

    gpath = Path(glossary) if glossary else config.find_glossary(root, cfg)
    md = gpath.read_text(encoding="utf-8") if gpath else ""
    ctx = {"rules": rules_text(mods, active, full=True, locales=cfg["locales"]), "rows": scan.glossary_rows(md),
           "aliases": scan.load_glossary(md), "mark": MARK}
    for n in chosen:
        if exports[n].get("needs") == "glossary" and not ctx["rows"]:
            print(f"skip  {n}: needs a ubiquitous-language glossary (none found; pass --glossary)")
            continue
        print(export_one(exports[n], root, ctx, dry_run, force))


# ---- cli -------------------------------------------------------------------

def run_list() -> None:
    root = config.project_root()
    mods = all_modules()
    active = resolve(mods, root, installed_plugins())
    for name, m in mods.items():
        on, why = active[name]
        print(f"{'on ' if on else 'off'}  {m['kind']:<6} {name:<18} {why:<32} {m.get('description', '')}")


STARTER = {
    "locales": ["en-CA"],
    "modules": {},
    "severity": {},
    "ignore_paths": [],
    "protected_terms": [],
}


def run_config(args) -> None:
    root = config.project_root()
    if args.action == "show":
        cfg = config.load(root)
        sources = cfg.pop("_sources")
        cfg.pop("_root")
        print(json.dumps(cfg, indent=2, ensure_ascii=False))
        print("\nset by: " + (", ".join(f"{k}={v}" for k, v in sources.items()) or "defaults only"), file=sys.stderr)
        return
    if args.action == "path":
        for layer in config.LAYERS:
            path = config.layer_path(layer, root)
            print(f"{layer:<8} {'exists ' if path.exists() else 'absent '} {path}")
        return
    layer = args.layer
    if args.action == "init":
        path = config.layer_path(layer, root)
        if path.exists():
            sys.exit(f"{path} already exists")
        return print(f"wrote {config.update_layer(layer, root, lambda d: d.update(STARTER))}")
    if args.action == "set":
        try:
            value = json.loads(args.value)
        except ValueError:
            value = args.value  # a bare word is a string: `config set inject full`
        keys = args.key.split(".")

        def change(data: dict) -> None:
            node = data
            for k in keys[:-1]:
                node = node.setdefault(k, {})
            node[keys[-1]] = value
        try:
            return print(f"{args.key} = {json.dumps(value, ensure_ascii=False)} in {config.update_layer(layer, root, change)}")
        except ValueError as e:
            sys.exit(f"not saved: {e}")


def selftest() -> None:
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        os.environ["CLAUDE_CONFIG_DIR"] = str(tmp / "cfg")
        root = tmp / "repo"
        (root / ".git" / "info").mkdir(parents=True)
        mdir = tmp / "mods"
        mdir.mkdir()
        (mdir / "alpha.md").write_text("---\nkind: rules\ndefault: auto\ndetect: ponytail\n---\nALPHA RULE\n")
        (mdir / "beta.md").write_text("---\nkind: rules\ndefault: on\n---\nBETA RULE\n")
        (mdir / "gamma.md").write_text(f"---\nkind: export\ntarget: out/g.md\n---\n<!-- {MARK} -->\n{{{{rules}}}}\n")
        (mdir / "Bad Name.md").write_text("ignored")
        mods = all_modules(mdir)
        assert set(mods) == {"alpha", "beta", "gamma"}, mods

        act = resolve(mods, root, set())
        assert act["alpha"][0] is False and act["beta"][0] is True
        assert resolve(mods, root, {"ponytail"})["alpha"][0] is True
        (mdir / "delta.md").write_text("---\ndefault: auto\ndetect_files: *.csproj, src/*.csproj, **/x\n---\nD\n")
        mods = all_modules(mdir)
        assert resolve(mods, root, set())["delta"][0] is False
        (root / "src").mkdir()
        (root / "src" / "App.csproj").write_text("")
        assert resolve(mods, root, set())["delta"] == (True, "default:auto (src/*.csproj)")
        (mdir / "delta.md").unlink()
        mods = all_modules(mdir)
        set_state("beta", "off", "user", root, mods)
        assert resolve(mods, root, set())["beta"] == (False, "user")
        set_state("beta", "on", "project", root, mods)
        assert resolve(mods, root, set())["beta"] == (True, "project")
        set_state("beta", "off", "local", root, mods)
        assert resolve(mods, root, set())["beta"] == (False, "local")
        set_state("beta", "reset", "local", root, mods)
        set_state("beta", "reset", "project", root, mods)
        assert resolve(mods, root, set())["beta"] == (False, "user")

        act = resolve(mods, root, {"ponytail"})
        text = rules_text(mods, act)
        assert "ALPHA RULE" not in text and "- alpha:" in text and "BETA RULE" not in text, text
        assert "ALPHA RULE" in rules_text(mods, act, full=True)
        text = rules_text(mods, act, locales=["en-CA", "fr-CA"])
        assert "Locales: en-CA:" in text and "fr -> " in text and "ste-fr.md" in text, text
        (mdir / "alpha.md").write_text("---\nkind: rules\ndefault: on\ninject: always\n---\nALPHA RULE\n")
        assert "ALPHA RULE" in rules_text(all_modules(mdir), act)

        ctx = {"rules": "RULES", "rows": [], "aliases": {}, "mark": MARK}
        g = dict(mods["gamma"])
        assert export_one(g, root, ctx, False, False).startswith("wrote")
        assert "RULES" in (root / "out/g.md").read_text()
        assert export_one(g, root, ctx, False, False).startswith("same")
        (root / "out/g.md").write_text("hand written")
        assert export_one(g, root, ctx, False, False).startswith("skip")
        g["target"] = "../escape.md"
        try:
            export_one(g, root, ctx, False, False)
            raise AssertionError("escape not blocked")
        except ValueError:
            pass

        once = upsert_block("# Agents\n\nmine\n", "OJ v1")
        twice = upsert_block(once, "OJ v2")
        assert "mine" in twice and "OJ v2" in twice and "OJ v1" not in twice and twice.count(BLOCK_START) == 1

        (root / "docs").mkdir()
        (root / "docs" / "Ubiquitous-Language.md").write_text("x")
        assert config.find_glossary(root).name == "Ubiquitous-Language.md"
        (root / "glossary.md").write_text("y")
        assert config.find_glossary(root, {"glossary": "glossary.md"}).name == "glossary.md"

    # every shipped module parses and every export target is safe
    for m in all_modules().values():
        assert m["kind"] in ("rules", "export") and m["default"] in config.STATES, m["name"]
        if m["kind"] == "export":
            safe_target(Path("/tmp/x"), m["target"])
        if m["kind"] == "rules":
            assert m.get("when"), f"{m['name']}: rules modules need a when: trigger"
    print("selftest ok")


def add_layer_flags(p) -> None:
    g = p.add_mutually_exclusive_group()
    g.add_argument("--project", dest="layer", action="store_const", const="project",
                   help="the repo's .claude/ocre-jelly.json (commit it to share with the team)")
    g.add_argument("--local", dest="layer", action="store_const", const="local",
                   help="the repo's .claude/ocre-jelly.local.json (personal, kept out of git)")
    p.set_defaults(layer="user")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--selftest", action="store_true")
    sub = ap.add_subparsers(dest="cmd")
    sub.add_parser("list")
    p = sub.add_parser("rules")
    p.add_argument("name", nargs="?", help="print one module's full rules")
    p.add_argument("--full", action="store_true", help="inline every active module instead of the index")
    for cmd in ("enable", "disable", "reset"):
        p = sub.add_parser(cmd)
        p.add_argument("name")
        add_layer_flags(p)
    p = sub.add_parser("config", help="show, init or set the layered JSON config")
    p.add_argument("action", choices=("show", "path", "init", "set"))
    p.add_argument("key", nargs="?", help="dotted key for set, e.g. locales or thresholds.sentence_words")
    p.add_argument("value", nargs="?", help='JSON value for set, e.g. \'["en-CA","fr-CA"]\' or 30')
    add_layer_flags(p)
    p = sub.add_parser("export")
    p.add_argument("names", nargs="*")
    p.add_argument("--glossary")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--force", action="store_true", help="overwrite files ocre-jelly did not generate")
    p = sub.add_parser("hook")
    p.add_argument("event", choices=("session-start", "subagent-start"))
    args = ap.parse_args()

    if args.selftest:
        return selftest()
    if args.cmd == "hook":
        try:
            return run_hook(args.event)
        except Exception as e:  # a broken module or config must never break session start
            print(f"ocre-jelly hook error: {e}", file=sys.stderr)
            return
    if args.cmd == "list":
        return run_list()
    if args.cmd == "rules":
        mods = all_modules()
        if args.name:
            if args.name not in mods:
                sys.exit(f"unknown module: {args.name}")
            return print(mods[args.name]["body"])
        root = config.project_root()
        return print(session_rules(root, config.load(root), args.full), end="")
    if args.cmd in ("enable", "disable", "reset"):
        state = {"enable": "on", "disable": "off", "reset": "reset"}[args.cmd]
        path = set_state(args.name, state, args.layer, config.project_root(), all_modules())
        return print(f"{args.name}: {state} in {path}")
    if args.cmd == "config":
        if args.action == "set" and (args.key is None or args.value is None):
            sys.exit("usage: config set KEY VALUE [--project|--local]")
        return run_config(args)
    if args.cmd == "export":
        return run_export(args.names, args.glossary, args.dry_run, args.force)
    ap.print_help()


if __name__ == "__main__":
    main()
